[package]
name = "rust-crud"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4"
mysql_async = { version = "0.33", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dotenv = "0.15"
